### ISSUE TITLE
Travis CI builds are not being executed

### ISSUE THREAD

**Issue by olaldiko** [lordmauve/flake8-html#25]
* flake8-html version: 0.4.1
* Python version: 3.9
* Operating System: Ubuntu 20.04

### Description

The Travis CI builds for the project are not being executed, as they need to be migrated to travis-ci.com.
I don't know if this is also affecting the release new versions or if tags need to be created manually.
Thanks!

### What I Did

Checked the travis build

**Comment by lordmauve** [comment]
Moved to GHA.
