### ISSUE TITLE
cannot import name 'Markup' from 'jinja2'

### ISSUE THREAD

**Issue by iuiu34** [lordmauve/flake8-html#27]
With the new release of jinja2, `markupsafe` has moved from 
`from jinja2 import markupsafe`
to
`from jinja2.utils import markupsafe`

In particular, running a fresh install of flake8-html throws error
`cannot import name 'Markup' from 'jinja2'`

current solution is install dependencies MarkupSafe==2.0.1, Jinja2==3.0.3.

**Comment by james-monkeyshines** [comment]
This was fixed in response to issue #23. What is lacking is a version bump that automated builds can detect - I've requested that in a new issue (#28).

**Comment by lordmauve** [comment]
I have released the new version including the fix for #23
