### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by james-monkeyshines** [lordmauve/flake8-html#28]
The issue with a deprecated Jinja2 import (#23) was quickly resolved, so thank you for that.

However, automated builds are still failing, because the flake8-html version has not been updated.

Please can you tag with an incremented version.

Many thanks,
James

**Comment by wesleybl** [comment]
@lordmauve can you please create a new release?

**Comment by lordmauve** [comment]
Yes, but I want to automate it with GHA and I haven't found time to do that yet.

**Comment by lordmauve** [comment]
I have set up automation and it has released.
