### ISSUE TITLE
Not compatible with flake8-5.0.0

### ISSUE THREAD

**Issue by sahilshah6196** [lordmauve/flake8-html#30]
* flake8-html version: 0.4.2
* Python version: 3.10
* Operating System: 

### Description

New version of flake8 was released (5.0.0): https://flake8.pycqa.org/en/latest/release-notes/5.0.0.html
flake8-html is not compatible with it and errors out with the following error:
```python
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/usr/local/lib/python3.10/site-packages/flake8/main/application.py", line 336, in run
    self._run(argv)
  File "/usr/local/lib/python3.10/site-packages/flake8/main/application.py", line 326, in _run
    self.report()
  File "/usr/local/lib/python3.10/site-packages/flake8/main/application.py", line 321, in report
    self.formatter.stop()
  File "/usr/local/lib/python3.10/site-packages/flake8_html/plugin.py", line 245, in stop
    self.write_index()
  File "/usr/local/lib/python3.10/site-packages/flake8_html/plugin.py", line 281, in write_index
    versions=self.option_manager.generate_versions(),
AttributeError: 'OptionManager' object has no attribute 'generate_versions'
```

### What I Did

Simply installed flake8 using a dockerfile with command:
```
RUN --mount=type=ssh pip install 'git+ssh://git@github.com/lordmauve/flake8-html.git' flake8 flake8-quotes flake8-unused-arguments
```

**Comment by izabela1337** [comment]
reproduced with python3.8, flake version 5.0.1 on ubuntu20

**Comment by iuiu34** [comment]
if the issue is not going to be solved soon, at least update the requirements in `setup.py` to
```py
requirements = [
    'jinja2>=3.1.0',
    'pygments>=2.2.0',
    'flake8>=3.3.0,<5.0.0',
    'importlib-metadata;python_version<"3.8"',
]
```

**Comment by thbeu** [comment]
Still not compatible with flake8 v6.0.0.

**Comment by nkuttler** [comment]
Is there some actively maintained fork?

**Comment by thbeu** [comment]
You might try with [v0.4.3](https://github.com/lordmauve/flake8-html/releases/tag/v0.4.3).

**Comment by nkuttler** [comment]
Thanks a lot, works for me!

**Comment by iuiu34** [comment]
Can [v0.4.3](https://github.com/lordmauve/flake8-html/releases/tag/v0.4.3) be installed from pypi?

**Comment by nkuttler** [comment]
@iuiu34 worked for me

**Comment by iuiu34** [comment]
last version is v0.4.2, is it not?
https://pypi.org/project/flake8-html/

**Comment by nkuttler** [comment]
Oh, you're right, I downloaded and installed manually, sorry

**Comment by JCHacking** [comment]
When will it be possible to get version 0.4.3 from pypi?

**Comment by lordmauve** [comment]
Hi, sorry, I tagged 0.4.3 but [release automation failed](https://github.com/lordmauve/flake8-html/actions/runs/3581833862). If anyone can help with fixing that I can do a release. I can't fix it myself at the moment because I don't have access to my laptop.

**Comment by jktjkt** [comment]
> Hi, sorry, I tagged 0.4.3 but [release automation failed](https://github.com/lordmauve/flake8-html/actions/runs/3581833862). If anyone can help with fixing that I can do a release. I can't fix it myself at the moment because I don't have access to my laptop.

https://github.com/lordmauve/flake8-html/pull/38

**Comment by skinitimski** [comment]
I pulled 0.4.3 today from pypi and it works great with flake8 6.x! 🥳
